export const DEFAULT_HIGH_THRESH = 0.2;
export const DEFAULT_MATCH_THRESH = 0.8;
export const DEFAULT_SECOND_MATCH_THRESH = 0.5;
export const DEFAULT_UNCONFIRMED_MATCH_THRESH = 0.7;
export const DEFAULT_NEW_TRACK_THRESH = 0.15;
export const DEFAULT_DUPLICATE_IOU_THRESH = 0.15;
export const DEFAULT_TRACK_BUFFER = 30;
